# Generated by Django 5.1.2 on 2024-12-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_csvfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='graph_link',
        ),
        migrations.AddField(
            model_name='article',
            name='csv_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.csvfile'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='file',
            field=models.FileField(upload_to='csv/'),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
