# Generated by Django 5.1.2 on 2024-12-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_apiendpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='api_endpoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.apiendpoint'),
        ),
    ]
