# Generated by Django 5.1.2 on 2024-12-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_apiendpoint_article_article_api_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='raw_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
