# Generated by Django 5.1.2 on 2024-12-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_apiendpoint_raw_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiendpoint',
            old_name='hashed_api_key',
            new_name='api_key',
        ),
        migrations.RemoveField(
            model_name='apiendpoint',
            name='raw_api_key',
        ),
    ]
