# Generated by Django 5.1.2 on 2024-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_hashed_api_key_apiendpoint_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='perex',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
