# Generated by Django 5.1.2 on 2024-12-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='measurement_unit',
            field=models.CharField(default='Počet', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='perex',
            field=models.TextField(default='', max_length=255),
        ),
    ]
