# Generated by Django 5.1.2 on 2024-12-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_measurement_unit_alter_article_perex'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='name',
            field=models.CharField(default='API Endpoint', max_length=255, unique=True),
        ),
    ]
