# Generated by Django 5.1.2 on 2024-12-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_apiendpoint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='apiendpoint',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
