# Generated by Django 5.1.2 on 2024-12-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_excelfile_uploaded_at_alter_apiendpoint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
