# Generated by Django 5.1.2 on 2024-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_excelfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
