# Generated by Django 5.1.2 on 2024-12-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_excelfile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
