# Generated by Django 5.1.2 on 2024-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_excelfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='file_url',
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(null=True, upload_to='excel'),
        ),
    ]
