# Generated by Django 5.1.2 on 2024-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_excelfile_file_url_alter_excelfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='csu_url',
            field=models.URLField(blank=True, default='https://vdb.czso.cz/vdbvo2/', null=True),
        ),
    ]
